version: "3.8"

services:
  bot:
    environment:
      - port=3000
      - botToken=6628056195:AAGtIwxg-BhEQAiSglM-HMV-Yg1LAYtokO8
      - cookie=_sd_public=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJlZDZhNTljZS1iNzBjLTQwNjctYmI2NC02OTIwMzEyZjM0NjMiLCJzdWIiOiI5ZDA2OWY3OC1jNDRjLTQ2ZGEtYjE3MC00NDg2ODdiN2Q0NmMiLCJpc3MiOiJLRVlNQVNURVIiLCJleHAiOjE3Mzg1MTQ1OTksImF1ZCI6IkdJR0FDSEFUX1BVQkxJQyIsImlhdCI6MTczODUxNDI4OSwic2lkIjoiOGViNTBhOTAtY2FiNy00NzAxLTlmNTAtODdlNjllYzVhNTYzIiwicHJvdmlkZXIiOiJBTk9OWU1PVVMifQ.s0GWj2B4tE836E6YMfeuZd671B8Pd0VdbnImbYYN-1VqI3CtjFgESCX0RkakJ-kID9Xazhau7FD1m7RiBFGTFmXfTnik3rYIAiGhuXXig9b57fF-h2nre5oQHaMzlze8VJq3Wya4TVn_sSue7DJATzrmE6c9sHA5bGBTXOB3FBMOtPrnWiuODqXgAUFB3UaA1lTsnb9frfTyqUo-0cHHRpEGVw5QSuJ_p9Ycap_VkhasXhrBqwZWMWlB70sexvAaAL0haLBT2zkkodAVXjVeD51h_nAFfqaukJQLM4Gnqc0vhtQVc-sn9xQ2Ms6JDeRKZf3RHio4enlBpkiRhb43IjZB3m8i3FnwuHg0u___Cp8X1iVvOlVvln3hf7RjFqO95_pwwcNUvLOYAFGMZMeZTH8CQttGgDJg7N1P_Qw76GLGQZS4SHltk7YLXr8Q_qdt88vjHaz2x_bEjy6kdovDUj1Cv0PNbC39jf8IfGBOyLT0LvBjxxZB_ztDlaT4iqoeGOXelYrF1f051WtufWeN42OHQUERzzEDoW4hvTsM9fl60ZxE0Nh5Mn_L_Jx-GBnYWL6AYq6ouWZU1RidFWaTgv59nSicVzGBulaZ4NfedfudFgGcGR7bbgJgAf8ugyQaZy-Ef9_MIrC2nt8l_AvbxQ0Clm81WMZXrJ-cB8b-9hc; _sd_user_id=9d069f78-c44c-46da-b170-448687b7d46c; bp_challenge=8bffc27e62e230942f2894f3b53feb58; _ym_uid=1738514298217959832; _ym_d=1738514298; _ym_isad=2; _ym_visorc=b; sticky_cookie_km=f5e5454e6e94ffe5; amp_ebe2ee=9d069f78-c44c-46da-b170-448687b7d46c...1ij3odtgt.1ij3oguk7.e.1.f; cookie_accepted=1
      - x-device-id=9d069f78-c44c-46da-b170-448687b7d46c
      - x-project-id=9d069f78-c44c-46da-b170-448687b7d46c
      - x-request-id=20b65c65-792d-44e1-8331-c7ba166fb522
      - x-sm-user-id=9d069f78-c44c-46da-b170-448687b7d46c
      - requestUrl=https://giga.chat/api/gigachat/smartproxy/api/gc-public/api/v0/sessions/c56cf806-3ff7-43a5-8319-098de3d411e0/request
    container_name: bot
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
    build:
      dockerfile: Dockerfile
    ports:
      - 18080:3000