version: "3.8"

services:
  bot:
    environment:
      - port=3000
      - botToken=6628056195:AAGtIwxg-BhEQAiSglM-HMV-Yg1LAYtokO8
    container_name: bot
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
    build:
      dockerfile: Dockerfile
    ports:
      - 18080:3000